### ISSUE TITLE
Feature request : hunt down rouge color

### ISSUE THREAD

**Issue by Raghav789** [themainingredient/colormate#56]
Although the originally the style guide generator of craft plug-in intended for dev handoff, I primarily used it for cleaning up design for near-match colors styles, etc
so basically craft used to scan the entire document and enlist all colors in a shape with their name in a page then whenever I find rouge color or near similar color I just change color of the shape to one I want, and hitting update would replace the color with new color throughout the document there will be one less color in the style guide.
I'm looking for something like this, my dev team is crying over for the color system

**Comment by Iar0** [comment]
Hey @Raghav789, thank you for the feedback!

What are you looking for is already in the future plans in the README, no release date is set but we're gonna look at it.

**Comment by Iar0** [comment]
@Raghav789 looks like the link above is wrong, you can download the latest version from here: Released in 1.5.0: https://github.com/themainingredient/colormate/releases. Even better, download it by using sketchpacks to stay up to date https://sketchpacks.com/themainingredient/colormate
