### ISSUE TITLE
fix: color breakdown does not shows all the levels

### ISSUE THREAD

**Issue by Iar0** [themainingredient/colormate#62]
Repro step:

1. open empty doc
2. create two rectangles with same color

Expected result: I should see two rectangles in the breakdown

![image](https://user-images.githubusercontent.com/8393332/56972897-1f765700-6b6c-11e9-9e17-b5db740f6d9e.png)

**Comment by SimoneFace** [comment]
Colormate does not pick up on layers that are named the same i..e if two layers are called "Rectangle" it will only display one of these layers in the result.

**Comment by Iar0** [comment]
Released in 1.5.0
