### ISSUE TITLE
Selecting Artboard

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#67]
When you select a child of an artboard, or its parent page, it does not centre on the correct area.

**Blockers:** Sketch SDK has known bug with regards centring on layers. Centring on artboard only works.

**Desired Solution:** 

**Option 1 (preferred solution):** When you select a child layer it centres the artboard, not the layer. The child layer is also selected in the Sketch layers panel.
Option 2:  Selecting a child layer should result in it's selection just in the Sketch layer panel.

**Comment by jeroenknol** [comment]
For now I have gone for option 2, selecting the layer when clicking on it, and only center on an artboard when clicked.

**Comment by SimoneFace** [comment]
@jeroenknol Update needed on this:

- The layer should be selectable but when you select a layer it should centre on the artboard it's child of.
