### ISSUE TITLE
Colorpicker view issue

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#68]
When I select the colorpicker, and I am on a colour that is scrolled further down the window pane, then the colorpicker does not scroll with me. Therefore I can't see it properly without scrolling away from the colour I was looking at. See pic:

<img width="369" alt="colormate" src="https://user-images.githubusercontent.com/43187821/59341784-c2dc8f00-8d08-11e9-83aa-b3d55a78492a.png">

**Comment by Iar0** [comment]
Released in 1.5.0: https://github.com/themainingredient/colormate/releases
