### ISSUE TITLE
Replace child colour only

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#70]
When I select a layer to change colour, then actually I replace the parent colour for all other layers that use this colour. However, as a designer I want to maybe just change "layer2" 's colour. So when I select a layer and replace colour it should just update this.

**Desired Solution:** 
As a user, when I select a child layer in colormate, then the colorpicker button should appear, indicating to me I can replace just this colour.

**Comment by Iar0** [comment]
Released in 1.5.0: https://github.com/themainingredient/colormate/releases
