### ISSUE TITLE
New shortcut for selection

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#73]
The selection tool works great but we probably need to make it clear in the colormate plugin that this is possible. So Simone will provide design for this. 

**Desired Solution:**
Create new shortcut to include "run on selection"
Update current shortcut to "Run on whole document"
<img width="490" alt="Screenshot 2019-06-12 at 14 21 21" src="https://user-images.githubusercontent.com/43187821/59350885-6f287080-8d1d-11e9-9496-04b7cb8368fb.png">

**Comment by SimoneFace** [comment]
@jeroenknol I will provide design for loader to include tip that you can run colormate on selection. I will also provide full screen as a flat asset for you as we still have font problem there.

**Comment by SimoneFace** [comment]
@jeroenknol please revert the shortcut back to "List all used colors"

**Comment by Iar0** [comment]
Released in 1.5.0: https://github.com/themainingredient/colormate/releases
