### ISSUE TITLE
Replacing colour - reordering of colours

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#76]
Currently all colours are ordered numerically in order to keep colour groups together i.e. all reds, greys etc.

However, when I replace a colour for example from red to white, then Colormate automatically reorders that colour so that it is now grouped with the other white/greys in the list of colours used. Therefore, as a user, if I want to adjust the colour again I don't know where it has gone or what it is called in order to do that. 

**Desired Solution:**

As a user, when I replace a colour it shouldn't reorder after I update it's colour. The next time I run Colormate is when it should be ordered in the correct place.

**Comment by Iar0** [comment]
Released in 1.5.0: https://github.com/themainingredient/colormate/releases
