### ISSUE TITLE
Announcement banner

### ISSUE THREAD

**Issue by SimoneFace** [themainingredient/colormate#85]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
We need an announcement banner in the plugin so we can reach current users. Will provide design.

**Comment by SimoneFace** [comment]
@Iar0 Design here: https://share.goabstract.com/e2ec31c4-21d5-40b3-8769-1d5b7f8d65bc?collectionLayerId=e61a077f-613f-44d8-8427-e19b4c27198a&mode=design

**Comment by michelepatrassi** [comment]
released in 1.6.0
